name: cmms_staff_mobile_flutter
description: "CMMS App for Staff Centre."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.9.0
  flutter_riverpod: ^2.3.6
  go_router: ^13.0.0
  shared_preferences: ^2.5.3
  flutter_dotenv: ^5.1.0
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/splash.png
    - assets/images/main_bg.png
    - assets/images/login_header.png